import { SUPABASE_URL, SUPABASE_KEY } from './config.js';
const app=document.getElementById('app');
const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(p)||0)/100);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={location:null,tables:[],table:null,categories:[],products:[],groups:[],options:[],cart:[],draft:null,editingKey:null,search:'',sheet:null,busy:false,order:null,token:null,poll:null};
const platformHost=h=>h==='localhost'||h==='127.0.0.1'||h==='cuego.co.uk'||h==='www.cuego.co.uk'||h==='cuego.vercel.app'||h.endsWith('.vercel.app');
export function isCustomerRoute(){let h=location.hostname.toLowerCase();return location.pathname.startsWith('/order/')||(!platformHost(h)&&!['manage.cuego.co.uk','admin.cuego.co.uk','display.cuego.co.uk'].includes(h));}
function parts(){let path=location.pathname.split('/').filter(Boolean);let custom=!platformHost(location.hostname.toLowerCase());let i=path.indexOf('table');let j=path.indexOf('status');return {custom,org:custom?null:path[1],slug:custom?null:(path[2]&&path[2]!=='table'?path[2]:null),table:i>=0?decodeURIComponent(path[i+1]||''):null,status:j>=0?path[j+1]:null,base:custom?'':`/order/${encodeURIComponent(path[1]||'')}${path[2]&&path[2]!=='table'?'/'+encodeURIComponent(path[2]):''}`};}
async function req(path,body){let r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method:body===undefined?'GET':'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error('The ordering service is temporarily unavailable. Please try again.');let t=await r.text();return t?JSON.parse(t):null}
const rows=(table,query)=>req(`${table}?${query}`);
function theme(){let l=state.location;document.documentElement.style.setProperty('--venue-primary',l.primary_colour);document.documentElement.style.setProperty('--venue-accent',l.accent_colour);document.title=`Order at ${l.name} | Cuego`;}
function brand(){let l=state.location;return `<div class="venue-brand">${l.logo_url?`<img src="${esc(l.logo_url)}" alt="${esc(l.name)}" onerror="this.style.display='none'">`:''}<strong>${esc(l.name)}</strong></div>`}
function powered(){return '<footer class="venue-powered">Powered by <a href="https://www.cuego.co.uk" aria-label="Cuego"><img src="/assets/cuego-logo.webp" alt="Cuego" width="1000" height="333" loading="lazy"></a></footer>'}
function show(html){app.innerHTML=html}
function baseScreen(inner){show(`<div class="venue-app">${inner}${powered()}</div>`)}
function statusMessage(msg){let el=document.querySelector('.venue-alert');if(el)el.textContent=msg;else alert(msg)}
function navigate(path){history.pushState({},'',path);initCustomer()}
function rememberKey(){return `cuego-table-${state.location.id}`}
function readRemembered(){try{let v=JSON.parse(localStorage.getItem(rememberKey())||'null');return v&&v.expires>Date.now()?state.tables.find(t=>t.id===v.id):null}catch{return null}}
function remember(table){localStorage.setItem(rememberKey(),JSON.stringify({id:table.id,expires:Date.now()+2*60*60*1000}))}
function cartKey(){return `cuego-cart-${state.location.id}-${state.table.id}`}
function loadCart(){try{state.cart=JSON.parse(sessionStorage.getItem(cartKey())||'[]');if(!Array.isArray(state.cart))state.cart=[];state.cart=state.cart.filter(x=>state.products.some(p=>p.id===x.item_id&&itemAvailable(p))&&x.option_ids.every(id=>state.options.some(o=>o.id===id&&o.available))&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=20)}catch{state.cart=[]}}
function saveCart(){sessionStorage.setItem(cartKey(),JSON.stringify(state.cart));sessionStorage.removeItem(cartKey()+'-pending')}
function tableEntry(){let remembered=readRemembered();baseScreen(`<main class="table-entry">${brand()}<section class="table-prompt"><p class="venue-kicker">Order to your table</p><h1>What table are you at?</h1><form data-cue-form="table"><label for="table-number">Table number</label><input id="table-number" name="table" type="text" inputmode="numeric" autocomplete="off" maxlength="30" placeholder="e.g. 12" required><button class="venue-button" type="submit">Continue</button></form>${remembered?`<button class="remember-table" data-cue-action="remember" data-table="${remembered.id}">Still at Table ${esc(remembered.label)}? Continue ordering</button>`:''}<p class="venue-alert" role="alert"></p></section></main>`)}
function confirmTable(table){state.sheet='confirm';document.body.classList.add('cue-sheet-open');let node=document.createElement('div');node.className='cue-sheet-wrap';node.innerHTML=`<button class="cue-scrim" data-cue-action="close" aria-label="Close"></button><section class="cue-sheet" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div class="cue-handle"></div><p class="venue-kicker">Check your table</p><h2 id="confirm-title">Table ${esc(table.label)}</h2><p>Your order will be brought to Table ${esc(table.label)}.</p><button class="venue-button" data-cue-action="confirm" data-table="${table.id}">Yes, that’s my table</button><button class="venue-text-button" data-cue-action="close">Change table</button></section>`;app.appendChild(node);node.querySelector('[data-cue-action="confirm"]').focus()}
function closeSheet(){state.sheet=null;document.body.classList.remove('cue-sheet-open');document.querySelector('.cue-sheet-wrap')?.remove()}
function tablePath(table){return `${parts().base}/table/${encodeURIComponent(table.label)}`}
async function loadMenu(){let id=encodeURIComponent(state.location.id);[state.categories,state.products,state.groups]=await Promise.all([rows('menu_categories',`venue_id=eq.${id}&select=*&order=sort_order.asc,name.asc`),rows('menu_items',`venue_id=eq.${id}&visibility=neq.hidden&select=*&order=sort_order.asc,name.asc`),rows('modifier_groups',`venue_id=eq.${id}&select=*&order=sort_order.asc`)]);let ids=state.groups.map(g=>g.id);state.options=ids.length?await rows('modifier_options',`group_id=in.(${ids.join(',')})&select=*&order=sort_order.asc`):[];loadCart();menu()}
function itemAvailable(p){return p.available&&p.visibility==='available'&&(p.stock_count===null||p.stock_count>0)}
function itemCount(){return state.cart.reduce((n,x)=>n+x.quantity,0)}
function itemPrice(line){let p=state.products.find(x=>x.id===line.item_id);return (p?.price_pence||0)+line.option_ids.reduce((n,id)=>n+(state.options.find(o=>o.id===id)?.price_delta_pence||0),0)}
function total(){return state.cart.reduce((n,x)=>n+itemPrice(x)*x.quantity,0)}
function menu(){let t=state.table,l=state.location,search=state.search.toLowerCase();let categories=[...state.categories,{id:null,name:'Other'}];let sections=categories.map(c=>({c,products:state.products.filter(p=>p.category_id===c.id&&(!search||`${p.name} ${p.description}`.toLowerCase().includes(search)))})).filter(x=>x.products.length);show(`<div class="venue-app menu-app"><header class="menu-header">${brand()}<div class="delivery-pill">Delivering to <strong>Table ${esc(t.label)}</strong></div></header><main class="menu-main"><div class="menu-title"><div><p class="venue-kicker">Table ${esc(t.label)}</p><h1>What can we get you?</h1></div><button class="table-change" data-cue-action="change-table">Change table</button></div><label class="menu-search-label" for="menu-search">Search menu</label><input class="menu-search" id="menu-search" type="search" placeholder="Search food and drinks" value="${esc(state.search)}"><nav class="category-strip" aria-label="Menu categories">${sections.map(({c})=>`<a href="#cat-${c.id||'other'}">${esc(c.name)}</a>`).join('')}</nav>${sections.length?sections.map(({c,products})=>`<section class="menu-category" id="cat-${c.id||'other'}"><h2>${esc(c.name)}</h2>${products.map(p=>`<article class="menu-product"><div><h3>${esc(p.name)}</h3>${p.description?`<p>${esc(p.description)}</p>`:''}${p.allergen_info?`<p class="allergen-note">Allergens: ${esc(p.allergen_info)}</p>`:''}<strong>${money(p.price_pence)}</strong></div>${itemAvailable(p)?`<button class="product-add" data-cue-action="add" data-id="${p.id}" aria-label="Add ${esc(p.name)}">+</button>`:'<span class="sold-out">Sold out</span>'}</article>`).join('')}</section>`).join(''):'<div class="menu-empty">No matching items. Try another search.</div>'}</main>${itemCount()?`<button class="floating-basket" data-cue-action="basket"><span>View order · ${itemCount()} item${itemCount()===1?'':'s'}</span><strong>${money(total())}</strong></button>`:''}${powered()}</div>`);}
function productSheet(id,editingKey=null){let p=state.products.find(x=>x.id===id);if(!p)return;let existing=editingKey?state.cart.find(x=>x.key===editingKey):null;state.editingKey=editingKey;state.draft={item_id:id,quantity:existing?.quantity||1,option_ids:[...(existing?.option_ids||[])]};state.sheet='product';document.body.classList.add('cue-sheet-open');let groups=state.groups.filter(g=>g.item_id===id);let wrap=document.createElement('div');wrap.className='cue-sheet-wrap';wrap.innerHTML=`<button class="cue-scrim" data-cue-action="close" aria-label="Close"></button><section class="cue-sheet product-sheet" role="dialog" aria-modal="true" aria-labelledby="product-title"><div class="cue-handle"></div><h2 id="product-title">${esc(p.name)}</h2>${p.description?`<p>${esc(p.description)}</p>`:''}${groups.map(g=>`<fieldset class="modifier-group" data-group="${g.id}"><legend>${esc(g.name)} <small>${g.min_choices?'Required':'Optional'} · Choose ${g.min_choices===g.max_choices?g.max_choices:`${g.min_choices}–${g.max_choices}`}</small></legend>${g.min_choices===0&&g.max_choices===1?`<label class="modifier-option"><input type="radio" name="group-${g.id}" value="" ${!state.draft.option_ids.some(id=>state.options.some(o=>o.id===id&&o.group_id===g.id))?'checked':''}><span>No thanks</span></label>`:''}${state.options.filter(o=>o.group_id===g.id&&o.available).map(o=>`<label class="modifier-option"><input type="${g.max_choices===1?'radio':'checkbox'}" name="group-${g.id}" value="${o.id}" ${state.draft.option_ids.includes(o.id)?'checked':''}><span>${esc(o.name)}</span><strong>${o.price_delta_pence>0?'+'+money(o.price_delta_pence):o.price_delta_pence<0?money(o.price_delta_pence):'Included'}</strong></label>`).join('')}</fieldset>`).join('')}<div class="product-sheet-bottom"><div class="quantity-control"><button data-cue-action="qty-minus" aria-label="Reduce quantity">−</button><span class="draft-qty">${state.draft.quantity}</span><button data-cue-action="qty-plus" aria-label="Increase quantity">+</button></div><button class="venue-button" data-cue-action="save-product">${editingKey?'Update order':'Add to order'}</button></div><p class="venue-alert" role="alert"></p></section>`;app.appendChild(wrap);wrap.querySelector('[data-cue-action="save-product"]').focus()}
function basket(){state.sheet='basket';document.body.classList.add('cue-sheet-open');let wrap=document.createElement('div');wrap.className='cue-sheet-wrap';wrap.innerHTML=`<button class="cue-scrim" data-cue-action="close" aria-label="Close"></button><section class="cue-sheet basket-sheet" role="dialog" aria-modal="true" aria-labelledby="basket-title"><div class="cue-handle"></div><div class="basket-heading"><h2 id="basket-title">Your order</h2><button data-cue-action="close" aria-label="Close basket">×</button></div><p>Delivering to <strong>Table ${esc(state.table.label)}</strong></p>${state.cart.map(line=>{let p=state.products.find(x=>x.id===line.item_id);return `<div class="basket-line"><div><strong>${line.quantity} × ${esc(p?.name||'Item')}</strong><small>${line.option_ids.map(id=>esc(state.options.find(o=>o.id===id)?.name||'')).join(', ')}</small><button data-cue-action="edit" data-key="${esc(line.key)}">Edit</button> · <button data-cue-action="remove" data-key="${esc(line.key)}">Remove</button></div><strong>${money(itemPrice(line)*line.quantity)}</strong></div>`}).join('')}<label class="venue-field">Order note (optional)<textarea id="order-note" maxlength="500" rows="2" placeholder="Anything the team should know?"></textarea></label><div class="basket-total"><strong>Total</strong><strong>${money(total())}</strong></div><p class="demo-disclosure">DEMO MODE · Your payment will be simulated. No money will be taken.</p><button class="venue-button" data-cue-action="demo-checkout" ${state.cart.length?'':'disabled'}>Complete demo order</button><p class="venue-alert" role="alert"></p></section>`;app.appendChild(wrap);wrap.querySelector('[data-cue-action="demo-checkout"]').focus()}
async function checkout(){if(state.busy||!state.location.demo_mode)return;state.busy=true;let button=document.querySelector('[data-cue-action="demo-checkout"]');if(button)button.disabled=true;let token=sessionStorage.getItem(cartKey()+'-pending')||crypto.randomUUID();sessionStorage.setItem(cartKey()+'-pending',token);let notes=document.getElementById('order-note')?.value||'';try{let id=await req('rpc/place_demo_order',{p_location_id:state.location.id,p_table_id:state.table.id,p_client_token:token,p_lines:state.cart.map(x=>({item_id:x.item_id,quantity:x.quantity,option_ids:x.option_ids})),p_customer_name:'',p_notes:notes});sessionStorage.setItem(`cuego-order-${id}`,token);sessionStorage.removeItem(cartKey());sessionStorage.removeItem(cartKey()+'-pending');state.cart=[];closeSheet();navigate(`${tablePath(state.table)}/status/${id}`)}catch{statusMessage('Sorry, we couldn’t send your order. Please check availability and try again.');if(button)button.disabled=false}finally{state.busy=false}}
async function orderStatus(id){let token=sessionStorage.getItem(`cuego-order-${id}`);if(!token){baseScreen(`<main class="table-entry">${brand()}<section class="table-prompt"><h1>Order not found</h1><p>Open the order on the device used to place it.</p><button class="venue-button" data-cue-action="order-more">Back to menu</button></section></main>`);return}state.token=token;async function refresh(){try{let order=await req('rpc/get_demo_order',{p_order_id:id,p_client_token:token});if(order){state.order=order;renderStatus()}}catch{}}await refresh();state.poll=setInterval(refresh,3000)}
function renderStatus(){let o=state.order;if(!o)return;let steps=['new','accepted','preparing','ready','delivered'];let current=steps.indexOf(o.status);baseScreen(`<main class="status-page">${brand()}<div class="status-tick">✓</div><p class="venue-kicker">Demo order received</p><h1>We’ve got your order.</h1><p>Order <strong>#${esc(o.id.slice(0,8).toUpperCase())}</strong> · Table <strong>${esc(o.table)}</strong></p><p class="demo-disclosure">DEMO PAYMENT SIMULATED · No money was taken.</p><ol class="order-progress">${steps.map((step,i)=>`<li class="${i<=current?'done':''}">${step==='new'?'Received':step==='accepted'?'Accepted':step==='preparing'?'Preparing':step==='ready'?'Ready':'Delivered'}</li>`).join('')}</ol><section class="status-summary"><h2>Your order</h2>${o.items.map(i=>`<p>${i.quantity} × ${esc(i.name)} <span>${money(i.price_pence*i.quantity)}</span></p>`).join('')}<strong>Total <span>${money(o.total_pence)}</span></strong></section><button class="venue-button" data-cue-action="order-more">Order more</button></main>`)}
export async function initCustomer(){clearInterval(state.poll);closeSheet();state.location=null;let p=parts();baseScreen('<main class="table-entry"><p>Loading menu…</p></main>');try{let loc=await req('rpc/resolve_ordering_location',{p_hostname:p.custom?location.hostname.toLowerCase().replace(/\.$/,''):null,p_organisation_slug:p.org,p_location_slug:p.slug});if(!loc){baseScreen('<main class="table-entry"><section class="table-prompt"><h1>Ordering unavailable</h1><p>Please check the venue link or ask a member of staff.</p></section></main>');return}state.location=loc;theme();state.tables=await rows('venue_tables',`venue_id=eq.${encodeURIComponent(loc.id)}&active=eq.true&select=id,label,area&order=label.asc`);if(!p.table){tableEntry();return}state.table=state.tables.find(t=>t.label.toLowerCase()===p.table.toLowerCase());if(!state.table){tableEntry();statusMessage('That table is not available. Please enter the number shown at your table.');return}remember(state.table);if(p.status){await orderStatus(p.status);return}if(!loc.demo_mode){baseScreen(`<main class="table-entry">${brand()}<section class="table-prompt"><h1>Ordering isn’t available yet</h1><p>Please order with the venue team.</p></section></main>`);return}await loadMenu()}catch{baseScreen('<main class="table-entry"><section class="table-prompt"><h1>Menu unavailable</h1><p>Sorry, we’re having trouble loading the menu. Please try again.</p><button class="venue-button" data-cue-action="retry">Try again</button></section></main>')}}

document.addEventListener('submit',e=>{let f=e.target.closest('[data-cue-form="table"]');if(!f)return;e.preventDefault();let label=f.elements.namedItem('table').value.trim();let t=state.tables.find(x=>x.label.toLowerCase()===label.toLowerCase());if(!t){statusMessage('We couldn’t find that table. Check the number and try again.');return}confirmTable(t)});
document.addEventListener('input',e=>{if(e.target.id==='menu-search'){state.search=e.target.value;let caret=e.target.selectionStart;menu();let input=document.getElementById('menu-search');input?.focus();input?.setSelectionRange(caret,caret)}});
document.addEventListener('click',async e=>{let b=e.target.closest('[data-cue-action]');if(!b)return;let action=b.dataset.cueAction;if(!state.location&&action!=='retry')return;
 if(action==='retry'){initCustomer();return}if(action==='close'){closeSheet();return}if(action==='change-table'){state.search='';navigate(parts().base||'/');return}if(action==='remember'){let t=state.tables.find(x=>x.id===b.dataset.table);if(t)navigate(tablePath(t));return}if(action==='confirm'){let t=state.tables.find(x=>x.id===b.dataset.table);if(t){remember(t);closeSheet();navigate(tablePath(t))}return}
 if(action==='add'){let p=state.products.find(x=>x.id===b.dataset.id);if(!p||!itemAvailable(p))return;if(state.groups.some(g=>g.item_id===p.id)){productSheet(p.id);return}let key=p.id+':';let found=state.cart.find(x=>x.key===key);if(found)found.quantity=Math.min(20,found.quantity+1);else state.cart.push({key,item_id:p.id,quantity:1,option_ids:[]});saveCart();menu();return}
 if(action==='basket'){basket();return}if(action==='edit'){let line=state.cart.find(x=>x.key===b.dataset.key);if(line){closeSheet();productSheet(line.item_id,line.key)}return}if(action==='remove'){state.cart=state.cart.filter(x=>x.key!==b.dataset.key);saveCart();closeSheet();menu();if(state.cart.length)basket();return}
 if(action==='qty-minus'||action==='qty-plus'){state.draft.quantity=Math.max(1,Math.min(20,state.draft.quantity+(action==='qty-plus'?1:-1)));document.querySelector('.draft-qty').textContent=state.draft.quantity;return}
 if(action==='save-product'){let p=state.products.find(x=>x.id===state.draft.item_id);let chosen=[...document.querySelectorAll('.product-sheet input:checked')].map(x=>x.value).filter(Boolean);for(let g of state.groups.filter(x=>x.item_id===p.id)){let count=chosen.filter(id=>state.options.some(o=>o.id===id&&o.group_id===g.id)).length;if(count<g.min_choices||count>g.max_choices){statusMessage(`Please choose ${g.name}.`);return}}let key=p.id+':'+chosen.sort().join(',');let existing=state.cart.find(x=>x.key===key&&x.key!==state.editingKey);let quantity=state.draft.quantity;if(state.editingKey)state.cart=state.cart.filter(x=>x.key!==state.editingKey);if(existing)existing.quantity=Math.min(20,existing.quantity+quantity);else state.cart.push({key,item_id:p.id,quantity,option_ids:chosen});saveCart();closeSheet();menu();return}
 if(action==='demo-checkout'){checkout();return}if(action==='order-more'){navigate(tablePath(state.table));return}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.sheet)closeSheet()});
