import { SUPABASE_URL, SUPABASE_KEY } from './config.js';
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((p||0)/100);
let timer,locationId,stations=[],selected,venue,orders=[],states=[],busy=false;
function session(){try{return JSON.parse(localStorage.getItem('cuego_session')||'null')}catch{return null}}
async function query(table,filter='',method='GET',body){let s=session();if(!s?.access_token)throw Error('Please sign in to Cuego management first.');let r=await fetch(`${SUPABASE_URL}/rest/v1/${table}${filter?'?'+filter:''}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',...(method==='PATCH'?{Prefer:'return=representation'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error('Could not load the display. Sign in again or check your connection.');let text=await r.text();return text?JSON.parse(text):null}
function shell(content){app.innerHTML=`<main class="display-app"><header class="display-top"><div><div class="display-brand"><img src="/assets/cuego-logo.webp" alt="Cuego" width="1000" height="333"><small>ORDER DISPLAY</small></div><h1>${esc(venue?.name||'Orders')}</h1></div><a href="/manage/${encodeURIComponent(venue?.slug||'')}" class="display-manage">Management</a></header>${content}</main>`}
function render(){let station=stations.find(x=>x.id===selected);let active=states.filter(x=>x.station_id===selected&&orders.some(o=>o.id===x.order_id&&!['delivered','cancelled'].includes(o.status)));active.sort((a,b)=>{let oa=orders.find(o=>o.id===a.order_id),ob=orders.find(o=>o.id===b.order_id);return new Date(oa.created_at)-new Date(ob.created_at)});shell(`<nav class="display-stations" aria-label="Preparation stations">${stations.map(s=>`<button data-station="${s.id}" class="${s.id===selected?'selected':''}">${esc(s.name)} <span>${states.filter(x=>x.station_id===s.id&&x.status!=='ready'&&orders.some(o=>o.id===x.order_id&&!['cancelled','delivered'].includes(o.status))).length}</span></button>`).join('')}</nav><div class="display-heading"><h2>${esc(station?.name||'Station')} orders</h2><span>Updates automatically</span></div><section class="display-grid" aria-live="polite">${active.length?active.map(x=>{let o=orders.find(y=>y.id===x.order_id),items=(o.order_items||[]).filter(i=>i.station_id===selected);let next={new:['accepted','Accept'],accepted:['preparing','Start preparing'],preparing:['ready','Mark ready']}[x.status];let deliver=x.status==='ready'&&o.status==='ready';return `<article class="display-card"><div class="display-card-head"><span class="display-badge">${o.order_kind==='demo'?'DEMO · SIMULATED':'ORDER'}</span><span>${new Date(o.created_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></div><h3>Table ${esc(o.venue_tables?.label||'—')}</h3><p class="display-order-id">#${o.id.slice(0,8).toUpperCase()} · ${esc(x.status.toUpperCase())}</p><ul>${items.map(i=>`<li><strong>${i.quantity} × ${esc(i.name_snapshot)}</strong>${(i.modifiers_snapshot||[]).map(m=>`<small>${esc(m.name)}</small>`).join('')}</li>`).join('')}</ul>${o.notes?`<p class="display-note">Note: ${esc(o.notes)}</p>`:''}<div class="display-card-foot"><strong>${o.order_kind==='demo'?'DEMO PAYMENT':money(o.total_pence)}</strong>${next?`<button data-progress="${x.order_id}" data-next="${next[0]}">${next[1]}</button>`:deliver?`<button data-deliver="${x.order_id}">Delivered</button>`:'<span class="display-ready">Ready ✓</span>'}</div></article>`}).join(''):'<div class="display-empty"><strong>All caught up</strong><p>New orders for this station will appear here.</p></div>'}</section>`)}
async function refresh(){if(!locationId)return;try{[orders,states]=await Promise.all([query('orders',`venue_id=eq.${locationId}&select=id,created_at,status,order_kind,payment_status,notes,total_pence,venue_tables(label),order_items(name_snapshot,quantity,modifiers_snapshot,station_id)&order=created_at.desc&limit=100`),query('order_station_states',`select=order_id,station_id,status&order=updated_at.desc`)]);render()}catch(e){if(!orders.length)shell(`<p role="alert">${esc(e.message)}</p><a href="/manage">Sign in</a>`)}}
export async function initDisplay(){clearInterval(timer);let slug=location.pathname.split('/').filter(Boolean)[1]||'';if(!session()){shell('<p>Please sign in to Cuego management to use this display.</p><a href="/manage">Sign in</a>');return}try{let venues=await query('venues','select=id,slug,name');venue=venues.find(x=>x.slug===slug)||venues[0];if(!venue){shell('<p>No venue is assigned to this account.</p><a href="/manage">Management</a>');return}locationId=venue.id;stations=await query('preparation_stations',`location_id=eq.${locationId}&active=eq.true&select=*&order=name.asc`);selected=stations[0]?.id;if(!selected){shell('<p>Add a preparation station in management to receive orders.</p>');return}await refresh();timer=setInterval(refresh,3000)}catch(e){shell(`<p role="alert">${esc(e.message)}</p><a href="/manage">Sign in</a>`)}}
document.addEventListener('click',async e=>{let station=e.target.closest('[data-station]');if(station){selected=station.dataset.station;render();return}let button=e.target.closest('[data-progress],[data-deliver]');if(!button||busy)return;busy=true;button.disabled=true;try{if(button.dataset.deliver)await query('orders',`id=eq.${button.dataset.deliver}&venue_id=eq.${locationId}`,'PATCH',{status:'delivered'});else await query('order_station_states',`order_id=eq.${button.dataset.progress}&station_id=eq.${selected}`,'PATCH',{status:button.dataset.next});await refresh()}catch(e){button.disabled=false;alert(e.message)}finally{busy=false}});
